# -*- coding: utf-8 -*-
"""individual project 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HMPvcHWeMztIxAhhRQJsnKTB_RvkQHeU
"""

import requests
import re
from datetime import datetime, timedelta

url = "https://appserv3.montgomerycollege.edu/cmsc-206/sample_www_error_log.txt"
response = requests.get(url)
log_data = response.text

regex = r"\[([^\]]+)\] .* Invalid Search Term Passed"

matches = re.findall(regex, log_data)


differences = []
for i in range(len(matches) - 1):
    timestamp1 = datetime.strptime(matches[i], "%a %b %d %H:%M:%S.%f %Y")
    timestamp2 = datetime.strptime(matches[i+1], "%a %b %d %H:%M:%S.%f %Y")
    difference = timestamp2 - timestamp1
    microseconds = difference.microseconds + 1000000 * difference.seconds
    differences.append(microseconds)

average_difference = sum(differences) / len(differences)
total_hits=len(differences)+1
print("Found",total_hits,"records")
print("Average time between invalid searches: {:.2f} microseconds".format(average_difference),"or about {:.2f} seconds".format(average_difference / 1000000))

till_maximum_seconds=(10000/(average_difference / 1000000))
till_maximum_minutes=till_maximum_seconds/60
remainder_seconds=till_maximum_seconds%60

print("At that rate, we will run out of searches in",int(till_maximum_minutes) , "minutes and",int(remainder_seconds) , "seconds",", or {:.2f} seconds".format(till_maximum_seconds))